config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: { confirmations: 'confirmations' }
  
  resources :profiles, only: [:new, :create, :show] do
    member do
      get :matches
      get :workouts
    end
  end
    
  resources :goals, only: [:new, :create]

  resources :exercises, only: [:new, :create, :show, :index]

  resources :workouts, only: [:new, :create, :show]

  resources :days, only: [:new, :create, :index]

  resources :gyms, only: [:index]

  resources :trainer_profiles, only: [:new, :create, :show]

  root to: 'pages#index'
end

app/models/profile.rb
class Profile < ApplicationRecord

  validates(
  :display_name,
  length: { in: 6..20},
  uniqueness: true,
  format: { with: /\A[a-zA-Z0-9]*\z/,
  message: "only allows letters and numbers" } 
  )
  validates :days, numericality: true, allow_nil: true

  validates :weight, numericality: { greater_than: 0 }, allow_nil: true

  validates_inclusion_of :experience, :in => ["", "Beginner", "Intermediate", "Expert"]

  mount_uploader :profile_picture, ProfilePictureUploader

  belongs_to :goal, optional: true

  belongs_to :customer

  belongs_to :workout, optional: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :customer_login, except: [:show]

  def new
    unless @profile
      @profile = Profile.new
    end
  end

  def create
    @profile = Profile.create(profile_params)
    unless @profile.id == nil
      redirect_to profile_path(@profile.id)
    else
      render action: :new
    end
  end

  def show
    @profile = Profile.find_by(customer_id: current_customer.id)  
    if @profile.workout_id
      @workout = @profile.workout
    end
  end

  def matches
    @workouts = Workout.where(
      "purpose= ? AND difficulty = ? AND day_count = ?", 
      current_customer_profile.goal.name,
      current_customer_profile.experience,
      current_customer_profile.days
    ).limit(5).offset(0).includes(:days).includes(:set_exercises).includes(:exercises)

    @workouts = @workouts.to_json(
      except: [:created_at, :updated_at], include: {
        days:{ only: [:name], include: {
      set_exercises: { only: [:sets, :reps], include: {
      exercise: {only: [:name]}}}}}}
      )
  
  end

  def workouts
    @profile = current_customer_profile
    @profile.workout_id = params[:workout_id]
    @profile.save
    redirect_to(profile_path(current_customer_profile.id))
  end

  private

  def profile_params
    params.require(:profile).permit(
      :customer_id,
      :display_name,
      :goal_id,
      :days,
      :experience,
      :weight
      )
  end

end

app/views/profiles/matches.html.haml
= react_component("Workoutlist", { workouts: @workouts })

app/views/profiles/new.html.haml
.form.grid
  %h2 Create a Profile

  .col.col-1-of-2    
    = render "shared/errors", locals: {model: @profile}

    = form_for @profile do |f|
      =f.hidden_field :customer_id, value: current_customer.id

      %fieldset
        = f.label :display_name
        = f.text_field :display_name
      %fieldset
        = f.label :goal_id
        = f.select :goal_id, Goal.all.map { |goal| [goal.name, goal.id] }
      %fieldset
        = f.label :weight, "Weight in Kg"
        = f.text_field :weight
      %fieldset
        = f.label :days, "How many days a week will you train?"
        = f.select :days, ["", 3, 4, 5]
      %fieldset
        = f.label :experience, "Level of experience"
        = f.select :experience, ["","Beginner", "Intermediate", "Expert"]

      %fieldset
        = f.submit "Submit"

  .col.col-1-of-2.form-information

    %p
      All profile information is private unless you choose to share it. It is only used for filtering workout results.

app/views/profiles/show.html.haml
.wrapper
  .grid

    .col.col-1-of-3.both-gutter.profile-pic
      - unless @profile.profile_picture.url == nil
        = image_tag @profile.profile_picture.url
      - else
        %p
          You haven't set a Profile Picture. Upload one here:
          =link_to "Upload a profile picture"
      

    .col.col-1-of-3.both-gutter.profile
      %dl
        %dd> 
          Name:
        %dt> 
          = @profile.display_name
        %dd>
          Goal:
        %dt>
          - if @profile.goal
            = @profile.goal.name
          - else
            You haven't chosen a Goal yet. Set one here:
            = link_to "Set a Goal!"
        %dd>
          Days per week:
        %dt>
          - if @profile.days
            = @profile.days
          - else
            You haven't set your days yet. Change that here:
            = link_to "Edit your profile"
        %dd>
          Experience:
        %dt>
          - if @profile.experience
            = @profile.experience
          - else
            You haven't set your experience yet. Change that here:
            = link_to "Edit your profile"
        %dd>
          Weight:
        %dt>
          - if @profile.weight
            = @profile.weight
          - else
            You haven't set your weight yet. Change that here:
            = link_to "Edit your profile"


    .col.col-1-of-3.workout
      -if @workout
        = render @workout
      -else
        = link_to "Find a Workout", matches_profile_path