config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: { confirmations: 'confirmations' }
  
  resources :profiles, only: [:new, :create, :show] do
    member do
      get :matches
      get :workouts
    end
  end
    
  resources :goals, only: [:new, :create]

  resources :exercises, only: [:new, :create, :show, :index]

  resources :workouts, only: [:new, :create, :show]

  resources :days, only: [:new, :create, :index]

  resources :gyms, only: [:index]

  resources :trainer_profiles, only: [:new, :create, :show]

  root to: 'pages#index'
end

app/models/trainer_profile.rb
class TrainerProfile < ApplicationRecord

  belongs_to :customer

  has_many :workouts

  has_many :days
end

app/controllers/trainer_profiles_controller.rb
class TrainerProfilesController < ApplicationController

  before_action :trainer_login

  def new
    @trainer_profile = TrainerProfile.new
  end

  def create
    @trainer_profile = TrainerProfile.create!(trainer_profile_params)
    redirect_to trainer_profile_path(@trainer_profile.id)
  end

  def show
    set_page
    @trainer_profile = TrainerProfile.find(params[:id])
    @limit = 3
    @workouts = @trainer_profile.workouts.limit(@limit).offset((@limit * (@page.to_i - 1)))
    @next_page = @page + 1
    @prev_page = @page - 1
    @final_page = (@workouts.count.to_f / @limit).ceil
  end

  private

  def trainer_profile_params
    params.require(:trainer_profile).permit(
      :customer_id,
      :name,
      :gym_name,
      :gym_postcode,
      :years_experience,
      :qualification,
      :rate,
      :bio
      )
  end

end

app/views/trainer_profiles/new.html.haml
.form.grid
  %h2 Create a Trainer Profile

  .col.col-1-of-2
    = form_for @trainer_profile do |f|
      =f.hidden_field :customer_id, value: current_customer.id
      %fieldset
        = f.label :name
        = f.text_field :name
      %fieldset
        = f.label :gym_name
        = f.text_field :gym_name
      %fieldset
        = f.label :gym_postcode
        = f.text_field :gym_postcode
      %fieldset
        = f.label :years_experience
        = f.text_field :years_experience
      %fieldset
        = f.label :qualification
        = f.text_field :qualification
      %fieldset
        = f.label :rate
        = f.text_field :rate
      %fieldset
        = f.label :bio
        = f.text_area :bio
      %fieldset
        = f.submit "Submit"

  .col.col-1-of-2.form-information

    %p
      All profile information is public to registered users of this site.

app/views/trainer_profiles/show.html.haml
.wrapper
  .grid
    .col.col-1-of-3.trainer-profile.both-gutter  
      %dl
        %dt>
          Name:
        %dd>
          = @trainer_profile.name
        %dt>
          Gym Name:
        %dd>
          = @trainer_profile.gym_name  
        %dt>
          Years Experience:
        %dd>
          = @trainer_profile.years_experience
        %dt>
          Qualification:
        %dd>
          = @trainer_profile.qualification
        %dt>
          Rate:
        %dd>
          = @trainer_profile.rate
        %dt>
          Bio:
        %dd>
          = @trainer_profile.bio
    .col.col-1-of-3.workouts.both-gutter
      -if @workouts == []
        There are no workouts to show
      -else
        =render @workouts
        #page-change.grid
          .next-prev.col.col-1-of-2
          - unless @prev_page == 0
            = link_to 'Prev', trainer_profile_path(id: @trainer_profile.id, page: @prev_page, limit: @limit), id: "prev-link"

            - (1..@final_page).each do |i| 
              = link_to "#{i}", trainer_profile_path(id: @trainer_profile.id, page: i, limit: @limit), class: ("selected" if @page == i)

            - unless @next_page == @final_page + 1 
              = link_to 'Next', trainer_profile_path(id: @trainer_profile.id, page: @next_page, limit: @limit), id: "next-link"

    - if current_customer.trainer
      .col.col-1-of-3.create-workout.both-gutter
        %h4
          Create Workouts by creating days of exercises and combining them to create a workout.
        =link_to "Make some Days", new_day_path
        =link_to "Review your current Days", days_path
        =link_to "Make a Workout", new_workout_path