config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: { confirmations: 'confirmations' }
  
  resources :profiles, only: [:new, :create, :show] do
    member do
      get :matches
      get :workouts
    end
  end
    
  resources :goals, only: [:new, :create]

  resources :exercises, only: [:new, :create, :show, :index]

  resources :workouts, only: [:new, :create, :show]

  resources :days, only: [:new, :create, :index]

  resources :gyms, only: [:index]

  resources :trainer_profiles, only: [:new, :create, :show]

  root to: 'pages#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FitnessApp
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    %link{ :href =>"https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz", :rel => "stylesheet" }
    %link{ :href => "https://fonts.googleapis.com/css?family=Roboto:300,400,500", :rel => "stylesheet" }
  %body
    %header
      .grid
        %h1.col.col-1-of-2 Workout Finder
        %nav.col.col-1-of-2
          %ol
            %li>
              = link_to "Home", root_path
            %li>
              = link_to "Exercises", exercises_path
            %li>
              = link_to "Find a Gym", gyms_path
            - if current_customer      
              %li#logged-in>
                -if current_customer.trainer
                  -if current_customer_profile
                    =link_to "Your Profile", trainer_profile_path(current_customer_profile.id)
                  -else
                    =link_to "Create a Profile", new_trainer_profile_path
                -else
                  -if current_customer_profile
                    =link_to "Your Profile", profile_path(current_customer_profile.id)
                  -else
                    =link_to "Create a Profile", new_profile_path
              %li#logged-in>
                =link_to "Log Out", destroy_customer_session_path
            - else 
              %li>
                = link_to "Log In", new_customer_session_path
              %li#sign-in>
                = link_to "New visitor sign up!", new_customer_registration_path
      %p.notice
        = notice
      %p.alert
        = alert
    %main    
      = yield
    %footer
      %p Exercise can lead to injury. You follow all plans listed on this website at your own risk.